services:
 nginx:
  container_name: nginx
  build:
   context: ./requirements/nginx/
  ports:
   - 4242:443
  networks: 
   - Inception
  depends_on:
   mariadb:
    condition: service_healthy
   wordpress:
    condition: service_healthy
  restart: always
  volumes:
   - volume-web:/var/www/html/

 mariadb:
  container_name: mariadb
  build:
   context: ./requirements/mariadb/
  networks: 
   - Inception
  healthcheck:
   test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
   interval: 5s
   timeout: 5s
   retries: 5
  restart: always
  environment:
   DB_NAME: ${DB_NAME} 
   DB_USER: ${DB_USER}
   DB_PASS: ${DB_PASS}
  volumes:
   - volume-db:/var/lib/mysql

 wordpress:
  container_name: wordpress
  build:
   context: ./requirements/wordpress/
  networks:
   - Inception
  depends_on:
   mariadb:
    condition: service_healthy
   redis:
    condition: service_healthy
  healthcheck:
   test: ["CMD-SHELL", "nc -z localhost 9000"]
   interval: 5s
   timeout: 5s
   retries: 5
  restart: always
  volumes:
   - volume-web:/var/www/html/
  environment:
   DB_NAME: ${DB_NAME} 
   DB_USER: ${DB_USER}
   DB_PASS: ${DB_PASS}
   DB_HOST: ${DB_HOST}
   WP_ADMIN: ${WP_ADMIN}
   WP_ADMIN_PASS: ${WP_ADMIN_PASS}
   WP_ADMIN_MAIL: ${WP_ADMIN_MAIL}
   WP_USER: ${WP_USER}
   WP_USER_PASS: ${WP_USER_PASS}
   WP_USER_MAIL: ${WP_USER_MAIL}
   WP_USER_ROLE: ${WP_USER_ROLE}
   WP_URL: ${WP_URL}
   WP_TITLE: ${WP_TITLE}

 adminer:
  container_name: adminer
  build:
   context: ./requirements/adminer/
  networks:
   - Inception
  depends_on:
   wordpress:
    condition: service_healthy
  volumes:
   - volume-web:/var/www/html/
  environment:
   DB_NAME: ${DB_NAME} 
   DB_USER: ${DB_USER}
   DB_PASS: ${DB_PASS}
   DB_HOST: ${DB_HOST}

 redis:
  container_name: redis
  build:
   context: ./requirements/redis/
  networks:
   - Inception
  healthcheck:
   test: ["CMD", "redis-cli", "ping"]
   interval: 5s
   timeout: 5s
   retries: 3
  restart: always

 vsftp:
  init: true
  container_name: vsftp
  build:
   context: ./requirements/vsFTP/
  networks:
   - Inception
  restart: always
  depends_on:
   - wordpress
  ports:
   - 2100:21
   - 21100-21110:21100-21110
  environment:
   FTP_USER: ${FTP_USER}
   FTP_PASS: ${FTP_PASS}

 static:
  container_name: website
  build:
   context: ./requirements/static/
  networks:
   - Inception
  volumes:
   - volume-web:/media/

networks:
 Inception:
  driver: bridge
 
volumes:
 volume-db:
  driver: local
  driver_opts:
   type: none
   o: bind
   device: /home/secros/data/db
 volume-web:
  driver: local
  driver_opts:
   type: none
   o: bind
   device: /home/secros/data/web
